import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import "./theme-config.css";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	);
}
